### PR TITLE
fix metadata reserved keys transform

### LINKED ISSUE #3832: Updates to Subjects error when update params do not contain metadata
Recently, the `SubjectsController#build_update_hash` method was updated to include a call to a new method:

https://github.com/zooniverse/panoptes/blob/e3949292f9510224cb3688bb362250bed7967d3a/app/controllers/api/v1/subjects_controller.rb#L178

for the purpose of ensuring that a specific set of metadata keys were downcased before an update, so that metadata cases like `#Priority`, would act as expected:

https://github.com/zooniverse/panoptes/blob/e3949292f9510224cb3688bb362250bed7967d3a/app/controllers/api/v1/subjects_controller.rb#L203-L209

This method assumes that `params[:metadata]` exists, which is not always true. We received a ticket in which a user was trying to update a subject's locations (adding a frame to an existing subject) via the python client. The request that this generated failed and a `NoMethodError: undefined method 'transform_keys!' for nil:NilClass` error was logged.

### PR DESCRIPTION
**Pull request by camallen**
fixes  #3832

fixes a bug introduced in #3815 - this PR will now skip the metadata reserved key transform when metadata params are not present in the update action.

# Review checklist

- [ ] First, the most important one: is this PR small enough that you can actually review it? Feel free to just reject a branch if the changes are hard to review due to the length of the diff.
- [ ] If there are any migrations, will they the previous version of the app work correctly after they've been run (e.g. the don't remove columns still known about by ActiveRecord).
- [ ] If anything changed with regards to the public API, are those changes also documented in the `apiary.apib` file?
- [ ] Are all the changes covered by tests? Think about any possible edge cases that might be left untested.

### CODE REVIEW

**Comment by lcjohnso** [comment]
FYI @zwolf -- Cam put in this bug fix this morning.
